services:
    webgroshi:
        container_name: webgroshi
        build:
            context: .
            args:
                GROSHI_SOCKET: http://localhost:8080
        ports:
            - "80:8080"
